# Generated by Django 5.2.8 on 2025-11-19 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "DEPOSIT"), ("withdraw", "WITHDRAWAL")],
                        max_length=225,
                        null=True,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("processing", "PROCESSING"),
                            ("processed", "PROCESSED"),
                        ],
                        default="PENDING",
                        max_length=225,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Transactions",
                "db_table": "Transactions",
                "indexes": [
                    models.Index(
                        fields=["user", "transaction_type", "status", "date_created"],
                        name="Transaction_user_id_a370c4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_amount", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wallets",
                "db_table": "Wallets",
                "indexes": [
                    models.Index(
                        fields=[
                            "user",
                            "available_amount",
                            "date_created",
                            "date_modified",
                        ],
                        name="Wallets_user_id_5a8788_idx",
                    )
                ],
            },
        ),
    ]
