# Generated by Django 4.0.4 on 2025-11-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_wallet_available_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name_plural': 'Wallets'},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type', 'status', 'date_created'], name='Transaction_user_id_a370c4_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'available_amount', 'date_created', 'date_modified'], name='Wallets_user_id_5a8788_idx'),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='Transactions',
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='Wallets',
        ),
    ]
