# Generated by Django 4.0.4 on 2025-11-19 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_type', models.CharField(choices=[('National ID', 'National ID'), ('International Passport', 'International Passport'), ('Voter ID', 'Voter ID'), ('Driving License', 'Driving License')], max_length=50)),
                ('kyc_number', models.CharField(max_length=20)),
                ('kyc_image', models.ImageField(blank=True, upload_to='media/')),
                ('kyc_status', models.BooleanField(default=False)),
                ('kyc_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'KYC',
                'db_table': 'KYC',
                'ordering': ['-kyc_date'],
            },
        ),
        migrations.AddIndex(
            model_name='kyc',
            index=models.Index(fields=['user', 'kyc_type', 'kyc_number', 'kyc_image', 'kyc_status', 'kyc_date'], name='KYC_user_id_97c0aa_idx'),
        ),
    ]
